### PR TITLE
Pull request for oobicpl-0.4.9

### PR DESCRIPTION
**Pull request by sandywang**
Dear Dr. Fonov,
I just updated codes to 0.4.9 following Claude's ChangeLog.
I also uploaded a specific version of m4 for autogen.sh because I cannot find a same tree from mni-acmacros.

Best,
Xindi

### CODE REVIEW

**Comment by vfonov** [comment]
you should make  pull requests against develop branch.

**Comment by gdevenyi** [comment]
develop also has m4 macros as a submodule which can hopefully avoid adding new m4. If not, please open up a PR against the mni-acmacros to add the missing material there.

**Comment by sandywang** [comment]
Can I create a branch of mni-acmacros for CIVET? I found some m4 files used by CIVET store here partly, 
https://github.com/BIC-MNI/minc/tree/master/m4

**Comment by gdevenyi** [comment]
Personally I would prefer if we didn't have differing branches floating around with different features, develop is where the most recent work is, and keeping it up to date with all changes would be best.

**Comment by vfonov** [comment]
m4 changes should go to https://github.com/BIC-MNI/mni-acmacros/tree/develop

**Comment by gdevenyi** [comment]
Hi, any chance of redoing these PRs and opening one against the acmacros repos?

**Comment by gdevenyi** [comment]
Closed in favour of #4

**Pull request closed without merging**
